### PR TITLE
4 user registration happy + sad paths

### LINKED ISSUE #4: User Registration (Happy + Sad Paths)
As a visitor,
when I visit the landing page and click on Sign Up,
I am taken to a Registration Page where I can register with my Google Account.

When my attempted registration is valid, I am redirected to my User Dashboard.

When my attempted registration is invalid, I am redirected to the Registration Page and I see an error indicating what went wrong during registration. (?)

### PR DESCRIPTION
**Pull request by SMcPhee19**
## Changes
- This PR closes #4 
- feat: add placeholder image for user register page
- chore: create controller methods for user registration happy path
- feat: create views for user registration happy path
- refactor: change the welcome page and routes to adhere to wireframes
- test: add user registration happy path
- All tests pass 

## Type of Changes
- [x] new feature
- [ ] setup
- [x] chore
- [ ] bug fix
- [x] refactor
- [ ] other: 

## Checklist
- [x] Tests added for new functionality
- [x] All other tests are also passing (please note if not) 
  - Current coverage %: 89.29
  - Of Note: Three of the four of us have discussed and are okay with the current test coverage, waiting for a potential refactor 

## Number of reviewers
- [x] 1
- [ ] 2
- [ ] 3

### CODE REVIEW

File: spec/features/users/register_spec.rb [hunk 1]
```diff
@@ -0,0 +1,42 @@
+require 'rails_helper'
+
+RSpec.describe "user registration" do
+  before :each do
+    visit sign_up_path
+  end
+
+  it 'as a user, I see a disclaimer about google' do
+    within '#disclaimer' do
+      expect(page).to have_content('RentInfrom uses Google for new user creation')
```
Comment (cariperi) [inline spec/features/users/register_spec.rb:10]:
```suggestion
      expect(page).to have_content('RentInform uses Google for new user creation')
```

**Review by cariperi — APPROVED** [review]
